CC=mpiicpc

# User-configured path
XMLPARSER_PATH=/gpfs1m/projects/uoa00322/david.shin/AdvXMLParser
CELLML_PATH=/gpfs1m/projects/uoa00322/david.shin/cellml-sdk	

CFLAGS=-I $(XMLPARSER_PATH) -I $(CELLML_PATH)/include -O
LFLAGS=-L $(XMLPARSER_PATH) -ladvxml -L $(CELLML_PATH)/lib -lcellml -lcis -Wl,-rpath=$(CELLML_PATH)/lib 

SOURCES=experiment.cpp virtexp.cpp utils.cpp cellml_observer.cpp distributor.cpp 
INCLUDES=virtexp.h utils.h GAEngine.h GAEngine.cpp cellml_observer.h distributor.h


all: experiment

experiment: $(SOURCES) $(INCLUDES)
	$(CC) $(CFLAGS) $(SOURCES) -o experiment $(LFLAGS)

clean:
	rm -f experiment *~ *.o
